#!/bin/bash

readonly PROGNAME=$(basename "$0")
readonly ARGS=("$@")

usage() {
    cat <<- EOF
	Usage: ${PROGNAME} [OPTIONS] FILE1 FILE2 [FILE3 [FILE4 ...]]

	Merge the given PDF files.

	Options:
	    -o --output         name of the output PDF file
	                        default: same as the first PDF file, but including
	                        "_merged" in its filename
	    -h --help           show this help
	EOF
}

main() {
    local outfile

    cmdline "${ARGS[@]}"

    outfile="${OUTFILE:-${INFILES[0]%.pdf}_merged.pdf}"

    merge_pdfs "${outfile}" "${INFILES[@]}"

    return
}

# Parse arguments
# (http://bit.ly/defensive-bash) (http://bit.ly/getopts_tutorial)
# $@ - all parameters given to the script
cmdline() {
    local arg=

    for arg; do
        case "${arg}" in
            # Translate --gnu-long-options to -g (short options)
            --help)         args="${args}-h " ;;
            --output)       args="${args}-o " ;;
            --*)            error "Unknown option ${arg}"; exit 1 ;;
            *)              # Pass through anything else
                            is equal "${arg:0:1}" "-" || arg="\"${arg}\""
                            args="${args}${arg} "
                            ;;
        esac
    done

    # Reset $@ to the short options
    eval set -- "${args}"

    while getopts ':ho:' arg; do
        case "${arg}" in
            h)  usage && exit 0 ;;
            o)  readonly OUTFILE=${OPTARG} ;;
            :)  error "-${OPTARG} needs an argument"; exit 1 ;;
            *)  error "Unknown option -${OPTARG}";exit 1 ;;
        esac
    done
    shift $((OPTIND-1))  # remove all options from $@

    # Handle non parameter arguments
    if is lt $# 2; then
        error 'At least two input PDF files are needed.'
        exit 1
    fi
    readonly INFILES=("$@")

    return 0
}

# $1 - output PDF filename
# $2 - array of input PDF filenames
merge_pdfs() {
    local outfile=$1 && shift
    local infiles=("$@")

    if is available pdftk; then
        pdftk "${infiles[@]}" cat output "${outfile}" dont_ask
        return $?
    else
        error 'pdftk is needed to merge PDFs.'
        exit 1
    fi
}


main
